global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-linux-bastion
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  reporting: true
tests:
  amznlinux:
    parameter_input: linux-bastion-master-amznlinux.json
    template_file: linux-bastion-master.template
