global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-linux-bastion
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  amznlinuxhvm:
    parameter_input: linux-bastion-master-amznlinuxhvm.json
    template_file: linux-bastion-master.template
  centos7hvm:
    parameter_input: linux-bastion-master-centos7hvm.json
    template_file: linux-bastion-master.template
  us1404hvm:
    parameter_input: linux-bastion-master-us1404hvm.json
    template_file: linux-bastion-master.template
  us1604hvm:
    parameter_input: linux-bastion-master-us1604hvm.json
    template_file: linux-bastion-master.template
